production:
  adapter: postgresql
  encoding: unicode
  username: postgres
  database: dde_new_master
  password: E21081988g
  host: localhost 

development:
  adapter: postgresql
  encoding: unicode
  username: postgres
  database: dde_person_evr_mtema
  password: E21081988g
  host: localhost 

test: &TEST
  adapter: mysql
  database: 
  username: test
  password: test
  host: localhost
evr:
  adapter: mysql2
  mysqlusername: test
  mysqlpassword: test
  database: dde_person_evr_mtema
  couchdb: dde_person_evr_mtema
  couchdb_port: 5984
  host: localhost
dde_npids:
  couchdb: dde_production
  couchdb_port: 5984
  host: localhost


cucumber:
  <<: *TEST